language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: '5.4'
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: '5.4'
      env: SYMFONY=2.8.*

    - php: '5.5'
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: '5.5'
      env: SYMFONY=2.8.*
    - php: '5.5'
      env: SYMFONY=3.0.*

    - php: '5.6'
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: '5.6'
      env: SYMFONY=2.8.*
    - php: '5.6'
      env: SYMFONY=3.0.*
    - php: '5.6'
      env: SYMFONY=3.1.*

    - php: '7.0'
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: '7.0'
      env: SYMFONY=2.8.*
    - php: '7.0'
      env: SYMFONY=3.0.*
    - php: '7.0'
      env: SYMFONY=3.1.*
    - php: '7.0'
      env: SYMFONY=dev-master

  allow_failures:
    - env: SYMFONY=dev-master

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;
  - composer self-update
  - if [ "$SYMFONY" != "" ]; then composer require "symfony/symfony:${SYMFONY}" --no-update; fi;

install:
  - composer update --prefer-dist --no-interaction ${COMPOSER_FLAGS}

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "zend_extension=xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;

script:
  - bin/phpunit

notifications:
  on_success: never
  on_failure: always
